In [1]:
import pandas as pd

In [3]:
info = pd.read_csv('~/summer26-twister/data/tidy_tornado_data.csv')

/tmp/ipykernel_260479/3571307361.py:1: DtypeWarning: Columns (0: TOR_OTHER_WFO, 1: TOR_OTHER_CZ_STATE, 2: TOR_OTHER_CZ_NAME) have mixed types. Specify dtype option on import or set low_memory=False.
  info = pd.read_csv('~/summer26-twister/data/tidy_tornado_data.csv')

In [4]:
info

,EPISODE_ID,EVENT_ID,STATE_FIPS,YEAR,MONTH_NAME,EVENT_TYPE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,...,BEGIN_AZIMUTH,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,DATA_SOURCE,YEARMONTH
0,2152355.0,5432062,32.0,2004,July,Tornado,0,0,0,0,...,N,RENO,8.0,N,NaN,NaN,NaN,NaN,PDS,2004-07-01
1,1182775.0,5430397,6.0,2004,December,Tornado,0,0,0,0,...,NaN,SANTA ROSA,NaN,NaN,38.45000,-122.70000,38.45000,-122.70000,PDS,2004-12-01
2,1182727.0,5430610,28.0,2004,December,Tornado,0,0,0,0,...,SW,DE KALB,2.0,SW,32.23333,-89.43333,32.28333,-89.38333,PDS,2004-12-01
3,1182686.0,5430497,18.0,2004,December,Tornado,0,0,0,0,...,SW,SANDUSKY,2.0,SW,39.40000,-85.50000,39.41667,-85.48333,PDS,2004-12-01
4,1183227.0,5431177,15.0,2004,February,Tornado,0,0,0,0,...,SE,PAHALA,2.0,SE,19.18333,-155.46667,19.41667,-155.23333,PDS,2004-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49432,2408261.0,5700830,40.0,1999,May,Tornado,0,0,0,0,...,S,BRAGGS,1.0,S,35.67000,-95.20000,35.67000,-95.20000,PDC,1999-05-01
49433,2409105.0,5704593,20.0,1999,June,Tornado,0,0,0,0,...,NW,LAKIN,22.0,NW,38.18000,-101.53000,38.17000,-101.53000,PDC,1999-06-01
49434,2409105.0,5704595,20.0,1999,June,Tornado,0,0,0,0,...,NW,LAKIN,22.0,NW,38.18000,-101.53000,38.17000,-101.53000,PDC,1999-06-01
49435,2409105.0,5704598,20.0,1999,June,Tornado,0,0,0,0,...,NW,LAKIN,19.0,NW,38.15000,-101.50000,38.15000,-101.50000,PDC,1999-06-01
49436,2409159.0,5703355,46.0,1999,June,Tornado,0,0,0,0,...,SW,KIMBALL,15.0,SW,43.60000,-99.17000,43.60000,-99.17000,PDC,1999-06-01

In [6]:
info[info['BEGIN_LAT'].isna() == False]

,EPISODE_ID,EVENT_ID,STATE_FIPS,YEAR,MONTH_NAME,EVENT_TYPE,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,...,BEGIN_AZIMUTH,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,DATA_SOURCE,YEARMONTH
1,1182775.0,5430397,6.0,2004,December,Tornado,0,0,0,0,...,NaN,SANTA ROSA,NaN,NaN,38.45000,-122.70000,38.45000,-122.70000,PDS,2004-12-01
2,1182727.0,5430610,28.0,2004,December,Tornado,0,0,0,0,...,SW,DE KALB,2.0,SW,32.23333,-89.43333,32.28333,-89.38333,PDS,2004-12-01
3,1182686.0,5430497,18.0,2004,December,Tornado,0,0,0,0,...,SW,SANDUSKY,2.0,SW,39.40000,-85.50000,39.41667,-85.48333,PDS,2004-12-01
4,1183227.0,5431177,15.0,2004,February,Tornado,0,0,0,0,...,SE,PAHALA,2.0,SE,19.18333,-155.46667,19.41667,-155.23333,PDS,2004-02-01
5,1190714.0,5431956,51.0,2004,September,Tornado,0,0,0,0,...,SE,MANASSAS,2.0,SE,38.73333,-77.46667,38.76667,-77.45000,PDS,2004-09-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49432,2408261.0,5700830,40.0,1999,May,Tornado,0,0,0,0,...,S,BRAGGS,1.0,S,35.67000,-95.20000,35.67000,-95.20000,PDC,1999-05-01
49433,2409105.0,5704593,20.0,1999,June,Tornado,0,0,0,0,...,NW,LAKIN,22.0,NW,38.18000,-101.53000,38.17000,-101.53000,PDC,1999-06-01
49434,2409105.0,5704595,20.0,1999,June,Tornado,0,0,0,0,...,NW,LAKIN,22.0,NW,38.18000,-101.53000,38.17000,-101.53000,PDC,1999-06-01
49435,2409105.0,5704598,20.0,1999,June,Tornado,0,0,0,0,...,NW,LAKIN,19.0,NW,38.15000,-101.50000,38.15000,-101.50000,PDC,1999-06-01
49436,2409159.0,5703355,46.0,1999,June,Tornado,0,0,0,0,...,SW,KIMBALL,15.0,SW,43.60000,-99.17000,43.60000,-99.17000,PDC,1999-06-01